plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.jetbrains.kotlin.android)
    id 'kotlin-kapt'
    alias(libs.plugins.google.gms.google.services)
    alias(libs.plugins.google.firebase.crashlytics)
}

android {
    namespace 'com.beautycam.hdcam.photoeditor'
    compileSdk 34

    defaultConfig {
        applicationId "com.beautycam.hdcam.photoeditor"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        def formattedDate = new Date().format('MM.dd.yyyy')
        archivesBaseName = "Beauty_Camera_HD_${versionName}_${versionCode}_${formattedDate}"
    }

    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = '1.8'
    }
    viewBinding {
        enabled = true
    }
    dataBinding {
        enabled = true
    }
}

dependencies {
    implementation project(':puzzlelayout')
    implementation project(':tedimagepicker')
    implementation project(':photoeditor')
    implementation libs.androidx.core.ktx
    implementation libs.androidx.appcompat
    implementation libs.material
    implementation libs.androidx.activity
    implementation libs.androidx.constraintlayout
    implementation libs.androidx.gridlayout
    implementation libs.firebase.config
    implementation libs.firebase.crashlytics
    testImplementation libs.junit
    androidTestImplementation libs.androidx.junit
    androidTestImplementation libs.androidx.espresso.core
////
    implementation 'com.google.android.play:review:2.0.1'
    // ViewModel & LiveData
    implementation "androidx.lifecycle:lifecycle-viewmodel-ktx:2.6.0"
    implementation "androidx.lifecycle:lifecycle-livedata-ktx:2.6.0"
    // KTX Extensions (có thể cần khi dùng với ViewModel, LiveData)
    implementation "androidx.lifecycle:lifecycle-runtime-ktx:2.6.0"

    implementation "androidx.fragment:fragment-ktx:1.6.1"
    ////
    implementation 'com.github.bumptech.glide:glide:4.16.0'
    annotationProcessor 'com.github.bumptech.glide:compiler:4.14.2'
////
    implementation "com.intuit.ssp:ssp-android:1.1.0"
    implementation "com.intuit.sdp:sdp-android:1.1.0"

    /////camera

    implementation("androidx.camera:camera-core:1.3.0")
    implementation("androidx.camera:camera-camera2:1.3.0")
    implementation("androidx.camera:camera-lifecycle:1.3.0")
    implementation("androidx.camera:camera-view:1.3.0")

    implementation "com.github.dcendents:android-maven-gradle-plugin:2.0"
    ///dialog color
    implementation "com.makeramen:roundedimageview:2.3.0"

    ///// db room
    implementation "androidx.room:room-runtime:2.6.1"
    kapt "androidx.room:room-compiler:2.6.1"
    implementation "androidx.room:room-ktx:2.6.1"

}